services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.local
    env_file:
      - ./frontend/.env
    ports:
      - "${FRONTEND_DEV_PORT}:5173"
      - "${FRONTEND_PREVIEW_PORT}:4173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.local
    env_file:
      - ./backend/.env
    ports:
      - "${BACKEND_PORT}:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - database

  database:
    image: postgres:18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: smart-room
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - ./data/database:/var/lib/postgresql

  pgadmin:
    image: dpage/pgadmin4:9
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "${PGADMIN_PORT}:80"
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    depends_on:
      - database
